const {chromium}=require('playwright');const fs=require('fs');
(async()=>{
 let src=fs.readFileSync('/home/claude/fitness-app/index.html','utf8').replace('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js','file:///home/claude/fitness-app/node_modules/jspdf/dist/jspdf.umd.min.js').replace('<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js"></script>','');
 fs.writeFileSync('/home/claude/fitness-app/_test.html','<!doctype html><html><head><meta charset=utf8><style>body{margin:0}[hidden]{display:none!important}</style></head><body>'+src+'</body></html>');
 const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});const p=await b.newPage({viewport:{width:390,height:844},deviceScaleFactor:2});p.setDefaultTimeout(5000);
 const errs=[];p.on('pageerror',e=>errs.push('PAGE '+e.message));p.on('console',m=>{if(m.type()==='error'&&!/ERR_|fonts/.test(m.text()))errs.push(m.text())});
 const log=[];const step=async(name,fn)=>{try{await Promise.race([fn(),new Promise((_,r)=>setTimeout(()=>r(new Error('step timeout')),15000))]);console.log('ok  '+name)}catch(e){console.log('FAIL '+name+': '+e.message.split('\n')[0]);await p.screenshot({path:'fail_'+name.replace(/[^a-z]+/g,'_').slice(0,30)+'.png'}).catch(()=>{});console.log('  view',await p.evaluate(()=>S.view+' sheet='+!!document.querySelector('#sheet:not([hidden])')).catch(()=>'?'))}};
 await p.goto('file:///home/claude/fitness-app/_test.html');await p.waitForTimeout(300);
 await step('onboarding empty name blocked',async()=>{await p.click('[data-act="create"]');if(!(await p.$('#obName')))throw new Error('proceeded without name')});
 await step('create profile -> new block sheet (no wizard)',async()=>{await p.fill('#obName','Danny');await p.click('[data-act="create"]');await p.waitForTimeout(200);if(await p.$('[data-goal]'))throw new Error('wizard still shown');if(!(await p.$('[data-nb="create"]')))throw new Error('no new block sheet')});
 await step('sheet closes via X and via backdrop',async()=>{await p.click('[data-closesheet]');await p.waitForTimeout(100);if(await p.$('.sheet'))throw new Error('X did not close');await p.click('[data-act="newProgram"]');await p.waitForTimeout(100);await p.click('.sheet-bg',{position:{x:5,y:5}});await p.waitForTimeout(100);if(await p.$('.sheet'))throw new Error('backdrop did not close');const cls=await p.evaluate(()=>document.body.className);if(/sheet-open/.test(cls))throw new Error('body class stuck')});
 await step('create hyrox program',async()=>{await p.click('[data-act="newProgram"]');await p.click('[data-nb="create"]');await p.click('[data-t="hyroxdanny"]');await p.click('[data-go]');await p.waitForTimeout(300);if(S_view=await p.evaluate(()=>S.view),S_view!=='today'&&S_view!=='home')throw new Error('view '+S_view);await p.evaluate(()=>{S.view='home';render()});await p.waitForTimeout(150)});
 await step('home renders: hubs + today card + intro',async()=>{const n=await p.$$eval('[data-hub]',x=>x.length);if(n!==3)throw new Error('hubs='+n);if(!(await p.$('[data-goto]')))throw new Error('no today card');await p.screenshot({path:'walk_home.png',fullPage:true})});
 await step('hub run/gym/wod render + periods',async()=>{for(const h of ['run','gym','wod']){await p.click('#tabs button[data-v="home"]');await p.waitForTimeout(80);await p.click(`[data-hub="${h}"]`);await p.waitForTimeout(150);if(S_view=await p.evaluate(()=>S.view),S_view!=='hub')throw new Error(h+' view='+S_view);const pd=await p.$('[data-pd="month"]');if(pd){await pd.click();await p.waitForTimeout(80)}await p.screenshot({path:'walk_hub_'+h+'.png',fullPage:true});const back=await p.$('[data-act="back"],[data-back]');if(back)await back.click()}await p.click('#tabs button[data-v="home"]')});
 await step('home → today',async()=>{await p.click('[data-goto]');await p.waitForTimeout(200);if(!(await p.$('.ovr,.hero')))throw new Error('no overview');await p.evaluate(()=>{S.date='2026-09-30';render()});await p.waitForTimeout(150)});
 await step('today has 2 sessions (wed)',async()=>{const n=await p.$$eval('.ovr,.hero',x=>x.length);if(n!==2)throw new Error('n='+n)});
 await step('overview link scrolls',async()=>{await p.click('.ovr')});
 await step('collapse/expand cardio',async()=>{const id=await p.$eval('[data-col]',e=>e.dataset.col);await p.click(`[data-col="${id}"]`);await p.waitForTimeout(100);const hidden=await p.$eval('.blocks',e=>e.hidden);if(!hidden)throw new Error('not collapsed');await p.click(`[data-col="${id}"]`)});
 await step('cardio auto-done on dist + fields',async()=>{await p.fill('[data-cf="rpe"]','7.5');await p.waitForTimeout(100);await p.fill('[data-cf="dist"]','12');await p.waitForTimeout(300);const st=await p.evaluate(()=>sessState(S.date,0));if(!st.done||st.dist!==12||st.rpe!==7.5)throw new Error(JSON.stringify(st))});

 await step('prefill is placeholder, tick fills value',async()=>{const v=await p.$eval('.ex[data-i="0"] input[data-f="w"][data-j="0"]',e=>[e.value,e.placeholder]);if(v[0]!==''||!v[1])throw new Error(JSON.stringify(v));await p.click('.ex[data-i="1"] [data-exall]');await p.waitForTimeout(100);const ok=await p.$$eval('.ex[data-i="1"] .ok.on',x=>x.length);const v2=await p.$eval('.ex[data-i="1"] input[data-f="w"][data-j="0"]',e=>e.value);if(ok!==3||!v2)throw new Error('exall '+ok+' '+v2);await p.click('.ex[data-i="1"] [data-exall]');await p.waitForTimeout(100);const ok2=await p.$$eval('.ex[data-i="1"] .ok.on',x=>x.length);if(ok2!==0)throw new Error('untick '+ok2)});
 await step('typed weight persists (tab, day, reload)',async()=>{await p.fill('.ex[data-i="2"] input[data-f="w"][data-j="0"]','42.5');await p.waitForTimeout(800);await p.click('#tabs button[data-v="stats"]');await p.waitForTimeout(100);await p.click('#tabs button[data-v="today"]');await p.waitForTimeout(150);await p.evaluate(()=>{S.date='2026-09-30';render()});await p.waitForTimeout(100);let v=await p.$eval('.ex[data-i="2"] input[data-f="w"][data-j="0"]',e=>e.value);if(v!=='42.5')throw new Error('after tab: '+v);await p.click('[data-nav="1"]');await p.click('[data-nav="-1"]');await p.waitForTimeout(100);v=await p.$eval('.ex[data-i="2"] input[data-f="w"][data-j="0"]',e=>e.value);if(v!=='42.5')throw new Error('after daynav: '+v);await p.reload();await p.waitForTimeout(400);await p.evaluate(()=>{S.view='today';S.date='2026-09-30';render()});await p.waitForTimeout(150);v=await p.$eval('.ex[data-i="2"] input[data-f="w"][data-j="0"]',e=>e.value);if(v!=='42.5')throw new Error('after reload: '+v);const ph=await p.$eval('.ex[data-i="2"] input[data-f="w"][data-j="1"]',e=>e.value+'|'+e.placeholder);console.log('set2',ph)});
 await step('log gym: tick all sets, add set, note',async()=>{for(const o of await p.$$('.ex[data-i="0"] [data-ok]'))await o.click();await p.click('.ex[data-i="0"] [data-addset]');await p.waitForTimeout(150);const n=await p.$$eval('.ex[data-i="0"] [data-ok]',x=>x.length);if(n!==4)throw new Error('sets='+n);await p.click('.ex[data-i="1"] [data-note]');await p.fill('.ex[data-i="1"] [data-notein]','stand 3')});
 await step('swap exercise with remember',async()=>{await p.click('.ex[data-i="2"] [data-swap]');await p.waitForTimeout(150);await p.click('#swRemember');await p.click('[data-f="all"]');await p.fill('#swq','row');await p.waitForTimeout(100);await p.click('#swlist [data-ex]');await p.waitForTimeout(200);const sw=await p.evaluate(()=>JSON.stringify(settings().swaps));if(!sw.includes('t2'))throw new Error('swap not remembered '+sw)});
 await step('add custom exercise via picker',async()=>{await p.click('.ex[data-i="3"] [data-swap]');await p.waitForTimeout(150);await p.click('[data-addnew]');await p.waitForTimeout(100);await p.click('[data-save]');if(!(await p.$('#nxErr:not([hidden])')))throw new Error('no validation');await p.fill('#nxName','Test cable row');await p.click('[data-save]');await p.waitForTimeout(200);const n=await p.evaluate(()=>settings().customEx.length);if(n!==1)throw new Error('customEx='+n)});
 await step('finish workout',async()=>{await p.click('[data-finish]');await p.waitForTimeout(200);await p.click('[data-pg="0:weight"]');await p.click('[data-yes]');await p.waitForTimeout(200);const d=await p.evaluate(()=>Object.values(S.sessions).filter(s=>s.done).length);if(d!==1)throw new Error('done='+d);const pn=await p.evaluate(()=>Object.values(S.sessions).find(s=>s.done).exercises[0].progNext);if(pn!=='weight')throw new Error('progNext='+pn)});
 await step('share sheet image+pdf (gym)',async()=>{const id=await p.evaluate(()=>Object.values(S.sessions).find(s=>s.done).id);await p.click(`[data-share="${id}"]`);await p.click('[data-img]');await p.waitForTimeout(300);if(!(await p.$('#sheet img')))throw new Error('no img');await p.click('[data-pdf]');await p.waitForTimeout(600);if(!(await p.$('#shOut a')))throw new Error('no pdf link');await p.click('.sheet-bg',{position:{x:5,y:5}})});

 await step('share link roundtrip + import',async()=>{const id=await p.evaluate(()=>Object.values(S.sessions).find(s=>s.done).id);const url=await p.evaluate(async id=>shareLinkFor(shareData(S.date,id)),id);if(!url.startsWith('https://dannydevrijer.github.io/Fitness-App/#w='))throw new Error(url);const code=url.split('#w=')[1];const pl=await p.evaluate(async c=>decodeShare(c),code);if(pl.items[0].kind!=='workout')throw new Error(JSON.stringify(pl).slice(0,100));
   const before=await p.evaluate(()=>Object.keys(prog().templates).length);await p.evaluate(u=>{location.hash=u.split('#')[1]},url);await p.evaluate(()=>checkShareHash());await p.waitForTimeout(400);await p.click('[data-imp]');await p.waitForTimeout(300);const after=await p.evaluate(()=>Object.keys(prog().templates).length);if(after!==before+1)throw new Error('tpl '+before+'->'+after);const ex=await p.evaluate(()=>(dayDoc(fmtKey(today())).extra||[]).length);if(ex<1)throw new Error('no extra');console.log('link length',url.length)});
 await step('garmin copy + share text',async()=>{const txt=await p.evaluate(()=>garminText(shareData(S.date,'day')));if(!/sets/.test(txt)&&!/km/.test(txt))throw new Error(txt.slice(0,80))});

 await step('add exercise to session + loose exercise on rest day',async()=>{const sid=await p.evaluate(()=>daySessions(S.date).find(s=>s.kind==='gym'&&!S.sessions[s.id]?.done)?.id);if(sid){const before=await p.evaluate(id=>S.sessions[id].exercises.length,sid);await p.click(`[data-sessactions="${sid}"] [data-addex]`);await p.waitForTimeout(150);await p.click('#swlist [data-ex]');await p.waitForTimeout(200);const after=await p.evaluate(id=>S.sessions[id].exercises.length,sid);if(after!==before+1)throw new Error('addex '+before+'->'+after)}
   await p.evaluate(()=>{S.date='2026-10-08';render()});await p.waitForTimeout(150);await p.click('[data-act="addExtra"]');await p.waitForTimeout(100);await p.click('[data-adhoc]');await p.waitForTimeout(150);await p.click('[data-f="legs"]');await p.click('#swlist [data-ex]');await p.waitForTimeout(250);const l=await p.evaluate(()=>daySessions(S.date));if(!l.some(x=>x.adhoc))throw new Error('no adhoc '+JSON.stringify(l));const n=await p.evaluate(()=>S.sessions[daySessions(S.date).find(x=>x.adhoc).id].exercises.length);if(n!==1)throw new Error('adhoc ex '+n);await p.click('.ex [data-exall]');await p.waitForTimeout(100);await p.click('[data-finish]');await p.waitForTimeout(150);await p.click('[data-yes]');await p.waitForTimeout(200);await p.screenshot({path:'walk_adhoc.png'});await p.evaluate(()=>{S.date=fmtKey(today());render()})});
 await step('extra session add/remove',async()=>{await p.click('[data-act="addExtra"]');await p.waitForTimeout(100);await p.click('[data-pick="t1"]');await p.waitForTimeout(200);const n=await p.$$eval('.ovr,.hero',x=>x.length);if(n!==4)throw new Error('n='+n);await p.click('[data-rmx="1"]');await p.waitForTimeout(150);const n2=await p.$$eval('.ovr,.hero',x=>x.length);if(n2!==3)throw new Error('n2='+n2)});
 await step('navigate days and jump today',async()=>{await p.click('[data-nav="1"]');await p.click('[data-nav="1"]');await p.click('[data-act="jumpToday"]');const d=await p.evaluate(()=>S.date);if(d!==fmt(new Date()))throw new Error(d)});
 await step('before/after program bounds',async()=>{await p.evaluate(()=>{S.date='2026-01-01';render()});const txt=await p.$eval('#main',e=>e.textContent);if(!/nog niet begonnen/.test(txt))throw new Error('no before msg');await p.evaluate(()=>{S.date='2027-01-01';render()});const t2=await p.$eval('#main',e=>e.textContent);if(!/afgelopen/.test(t2))throw new Error('no after msg');await p.evaluate(()=>{S.date=fmtKey(today());render()})});
 await step('schema: open week, go to day, back',async()=>{await p.click('#tabs button[data-v="schema"]');await p.waitForTimeout(150);await p.click('[data-w="5"]');await p.waitForTimeout(100);await p.click('[data-go]');await p.waitForTimeout(150);if(!(await p.$('[data-act="backSchema"]')))throw new Error('no back');await p.click('[data-act="backSchema"]');await p.waitForTimeout(100);if(!(await p.$('[data-w]')))throw new Error('not back')});
 await step('stats all tabs',async()=>{await p.click('#tabs button[data-v="stats"]');for(const st of ['overview','muscles','load','prs','ex']){await p.click(`[data-st="${st}"]`);await p.waitForTimeout(100)}await p.click('[data-st="overview"]');for(const pd of ['month','3m','6m','12m','all','week']){await p.click(`[data-pd="${pd}"]`);await p.waitForTimeout(80)}await p.click('[data-sharerecap]');await p.waitForTimeout(200);if(!(await p.$('#sheet img')))throw new Error('no recap img');await p.click('.sheet-bg',{position:{x:5,y:5}})});
 await step('settings: language switch and back',async()=>{await p.click('#tabs button[data-v="settings"]');await p.waitForTimeout(100);await p.click('[data-mt="prefs"]');await p.waitForTimeout(100);await p.click('[data-lang="en"]');await p.waitForTimeout(100);const txt=await p.$eval('#tabs',e=>e.textContent);if(!/Today/.test(txt))throw new Error('not english');await p.click('[data-lang="nl"]');await p.waitForTimeout(100);await p.click('[data-mt="plans"]');await p.waitForTimeout(100)});
 await step('cardio editor: run with intervals',async()=>{await p.evaluate(()=>openEditor(prog().id));await p.waitForTimeout(150);await p.screenshot({path:'walk_editor.png'});const addBtn=await p.$('[data-adds]');if(!addBtn)throw new Error('no add session btn');await addBtn.click();await p.waitForTimeout(150);await p.click('[data-newc="run"]');await p.waitForTimeout(150);await p.screenshot({path:'walk_cardio_editor.png',fullPage:true});
   await p.click('[data-rt="interval"]').catch(()=>{});await p.waitForTimeout(60);const f=async(sel,v)=>{const e=await p.$(sel);if(e)await e.fill(v)};await f('#ceN','6');await f('#ceWork','1000');await f('#ceRec','90');await f('#cePace','4:30');await f('#ceWu','10');await f('#ceCd','10');await p.waitForTimeout(100);const desc=await p.$eval('#ceLines',e=>e.value).catch(()=>'');console.log('gen lines:',desc.slice(0,120));await p.click('[data-savec]');await p.waitForTimeout(200);const lib=await p.evaluate(()=>(prog().cardioLib||[]).length);if(lib!==1)throw new Error('cardioLib='+lib);const last=await p.evaluate(()=>{const p=prog();const w=p.weeks[S.editor.week-1];return JSON.stringify(Object.values(w.days).flat().find(s=>s.runType))});if(!last)throw new Error('no run session saved');console.log('saved run:',last.slice(0,200))});
 await step('cardio editor: wod amrap',async()=>{await p.click('[data-adds]');await p.waitForTimeout(150);await p.click('[data-newc="wod"]');await p.waitForTimeout(150);await p.click('[data-fm="amrap"]').catch(()=>{});const f=async(sel,v)=>{const e=await p.$(sel);if(e)await e.fill(v)};await f('#ceDur','20');await p.click('[data-madd="Wall Balls"]');await p.waitForTimeout(80);await f('[data-mq="0"]','15');await p.click('[data-madd="SkiErg"]');await p.waitForTimeout(80);const mn=await p.$$('[data-mn]');console.log('mov inputs',mn.length);await f('[data-mq="1"]','250');await p.$eval('[data-mu="1"]',e=>{e.value='m';e.dispatchEvent(new Event('change'))});await p.waitForTimeout(100);await p.screenshot({path:'walk_wod_editor.png',fullPage:true});await p.click('[data-savec]');await p.waitForTimeout(200);const w=await p.evaluate(()=>{const p=prog();const w=p.weeks[S.editor.week-1];return JSON.stringify(Object.values(w.days).flat().find(s=>s.format))});if(!w)throw new Error('no wod saved');console.log('saved wod:',w.slice(0,220))});
 await step('editor: new workout template with exercises',async()=>{await p.click('[data-newtpl]');await p.waitForTimeout(100);await p.click('[data-save]');if(!(await p.$('#teErr:not([hidden])')))throw new Error('no validation');await p.fill('#teName','Benen');await p.click('[data-add]');await p.waitForTimeout(100);await p.click('[data-f="legs"]');await p.click('#swlist [data-ex]');await p.waitForTimeout(150);await p.click('[data-save]');await p.waitForTimeout(150);const n=await p.evaluate(()=>Object.keys(prog().templates).length);if(n!==4)throw new Error('tpls='+n)});
 await step('program share to profile + copy text',async()=>{await p.click('#pchip');await p.fill('#npName','Lisa');await p.click('[data-add]');await p.waitForTimeout(200);await p.click('.sheet-bg',{position:{x:5,y:5}}).catch(()=>{});await p.evaluate(()=>{closeSheet();switchProfile('danny')});await p.click('#tabs button[data-v="settings"]');await p.waitForTimeout(100);await p.click('[data-sharetpl]');await p.waitForTimeout(100);await p.click('[data-to="lisa"]');await p.waitForTimeout(200);const n=await p.evaluate(()=>Object.keys(S.programs).filter(k=>k.startsWith('lisa__')).length);if(n!==1)throw new Error('lisa progs='+n);await p.evaluate(()=>switchProfile('lisa'));await p.waitForTimeout(150);const tl=await p.evaluate(()=>Object.values(prog().templates).length);if(tl!==1)throw new Error('lisa tpl='+tl);await p.evaluate(()=>switchProfile('danny'))});
 await step('delete program safety',async()=>{await p.click('#tabs button[data-v="settings"]');await p.waitForTimeout(100);await p.click('[data-act="newProgram"]');await p.click('[data-nb="create"]');await p.click('[data-t="empty"]');await p.fill('#npName','Tijdelijk');await p.click('[data-go]');await p.waitForTimeout(200);await p.click('[data-act="back"]');await p.click('#tabs button[data-v="settings"]');await p.waitForTimeout(100);const before=await p.evaluate(()=>myPrograms().length);const id=await p.evaluate(()=>settings().activeProgram);await p.click(`[data-delp="${id}"]`);await p.click('[data-no]');const mid=await p.evaluate(()=>myPrograms().length);if(mid!==before)throw new Error('deleted on cancel');await p.click(`[data-delp="${id}"]`);await p.click('[data-yes]');await p.waitForTimeout(150);const after=await p.evaluate(()=>myPrograms().length);if(after!==before-1)throw new Error('not deleted');const act=await p.evaluate(()=>settings().activeProgram);if(!act)throw new Error('no active after delete')});
 await step('reload persists',async()=>{await p.reload();await p.waitForTimeout(400);const d=await p.evaluate(()=>({pid:S.pid,progs:myPrograms().length,done:Object.values(S.sessions).filter(s=>s.done).length}));if(d.pid!=='danny'||d.done!==1)throw new Error(JSON.stringify(d))});

 await step('more: prefs tab, rpe off, bodyweight log',async()=>{await p.click('#tabs button[data-v="settings"]');await p.waitForTimeout(100);await p.click('[data-mt="prefs"]');await p.waitForTimeout(100);await p.click('[data-rpe="0"]');await p.waitForTimeout(100);await p.fill('#bwIn','82.4');await p.click('[data-bwadd]');await p.waitForTimeout(150);const n=await p.evaluate(()=>settings().bwLog.length);if(n!==1)throw new Error('bw='+n);await p.screenshot({path:'walk_prefs.png'});await p.click('#tabs button[data-v="today"]');await p.waitForTimeout(150);const cols=await p.$$eval('.sets.norpe',x=>x.length);if(!cols)throw new Error('rpe still shown');await p.screenshot({path:'walk_today.png'})});
 await step('template editor reorder',async()=>{await p.click('#tabs button[data-v="settings"]');await p.waitForTimeout(100);await p.click('[data-mt="plans"]');await p.waitForTimeout(100);await p.click('[data-edittpl]');await p.waitForTimeout(150);const before=await p.$eval('[data-pick="0"]',e=>e.textContent);await p.click('[data-mv="0:1"]');await p.waitForTimeout(100);const after=await p.$eval('[data-pick="1"]',e=>e.textContent);if(before!==after)throw new Error('not moved');await p.click('[data-save]');await p.waitForTimeout(100)});

 await step('manual PR exercise + custom',async()=>{await p.click('#tabs button[data-v="stats"]');await p.waitForTimeout(100);await p.click('[data-st="prs"]');await p.waitForTimeout(100);await p.click('[data-addpr]');await p.waitForTimeout(100);await p.click('[data-save]');if(!(await p.$('#prErr:not([hidden])')))throw new Error('no validation');await p.click('[data-pickex]');await p.waitForTimeout(100);await p.fill('#swq','bench press');await p.waitForTimeout(80);await p.click('#swlist [data-ex]');await p.waitForTimeout(150);await p.fill('#prW','140');await p.fill('#prR','1');await p.click('[data-save]');await p.waitForTimeout(150);await p.click('[data-addpr]');await p.click('[data-k="custom"]');await p.fill('#prName','Hyrox Amsterdam');await p.fill('#prVal','1:12:30');await p.click('[data-save]');await p.waitForTimeout(150);const n=await p.evaluate(()=>settings().manualPrs.length);if(n!==2)throw new Error('prs='+n);await p.screenshot({path:'walk_prs.png'});for(const pd of ['all','12m']){await p.click(`[data-pd="${pd}"]`);await p.waitForTimeout(80)}await p.click('[data-delpr]');await p.click('[data-yes]');await p.waitForTimeout(100);const n2=await p.evaluate(()=>settings().manualPrs.length);if(n2!==1)throw new Error('del')});
 await step('stats overview screenshot',async()=>{await p.click('[data-st="overview"]');await p.click('[data-pd="month"]');await p.waitForTimeout(150);await p.screenshot({path:'walk_stats.png'})});

 await step('delete profile: double confirm, name mismatch, then delete',async()=>{await p.evaluate(()=>switchProfile('lisa'));await p.waitForTimeout(150);await p.click('#pchip');await p.waitForTimeout(100);await p.click('[data-del]');await p.waitForTimeout(100);await p.click('[data-no]');if(await p.evaluate(()=>!S.profiles.lisa))throw new Error('deleted on cancel');await p.click('#pchip');await p.waitForTimeout(100);await p.click('[data-del]');await p.waitForTimeout(100);await p.click('[data-yes]');await p.waitForTimeout(100);await p.fill('#delName','Piet');await p.click('[data-yes]');if(!(await p.$('#delErr:not([hidden])')))throw new Error('no mismatch error');if(await p.evaluate(()=>!S.profiles.lisa))throw new Error('deleted on mismatch');await p.fill('#delName','lisa');await p.click('[data-yes]');await p.waitForTimeout(200);const d=await p.evaluate(()=>({has:!!S.profiles.lisa,pid:S.pid,left:Object.keys(S.programs).filter(k=>k.startsWith('lisa__')).length}));if(d.has||d.pid!=='danny'||d.left)throw new Error(JSON.stringify(d))});

 await step('create program mid-way (week 2)',async()=>{await p.click('#tabs button[data-v="settings"]');await p.waitForTimeout(100);await p.click('[data-mt="plans"]');await p.waitForTimeout(100);await p.click('[data-act="newProgram"]');await p.click('[data-nb="create"]');await p.click('[data-t="ppl"]');await p.click('[data-sp="mid"]');await p.selectOption('#npCurW','2');await p.waitForTimeout(100);const hint=await p.$eval('#npMidHint',e=>e.textContent);await p.click('[data-go]');await p.waitForTimeout(300);const pl=await p.evaluate(()=>planFor(today()));if(!pl||pl.w!==2)throw new Error('week='+JSON.stringify(pl)+' '+hint);await p.screenshot({path:'walk_mid.png'})});
 await step('hero shows next session',async()=>{await p.click('#tabs button[data-v="today"]');await p.waitForTimeout(150);await p.evaluate(()=>{S.date='2026-10-08';render()});await p.waitForTimeout(150);if(!(await p.$('.hero')))throw new Error('no hero');await p.screenshot({path:'walk_hero.png'})});
 function fmt(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
 await step('final screenshots with data',async()=>{await p.evaluate(()=>{S.date=fmtKey(today());S.view='home';render()});await p.waitForTimeout(200);await p.screenshot({path:'fin_home.png',fullPage:true});for(const h of ['run','gym','wod']){await p.evaluate(h=>{S.hub=h;S.view='hub';S.period='all';render()},h);await p.waitForTimeout(200);await p.screenshot({path:'fin_hub_'+h+'.png',fullPage:true})}await p.evaluate(()=>{S.date='2026-09-30';S.view='today';render()});await p.waitForTimeout(200);await p.screenshot({path:'fin_today.png',fullPage:true});const recs=await p.evaluate(()=>recommendations().map(r=>r.text||JSON.stringify(r)));console.log('recs',recs)});
 console.log(log.join('\n'));console.log('errors',errs);await b.close();
})();
